---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static-deployment
  namespace: playground
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-static
  template:
    metadata:
      labels:
        app: nginx-static
    spec:
      automountServiceAccountToken: false
      containers:
      - name: nginx-static
        image: rlewan/nginx-static:6d1849765ee89d9f4c4eee2e8281acb3d0a86922
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10    # delay after container start and before first liveness probe
          failureThreshold: 10    # times before giving up (before restart pod)
        readinessProbe:
          httpGet:
            path: /
            port: 80
