---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static-deployment
  namespace: playground
  labels:
    name: nginx-static
  annotations:
    flux.weave.works/automated: true
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-static
  template:
    metadata:
      labels:
        name: nginx-static
    spec:
      automountServiceAccountToken: false
      containers:
      - name: nginx-static
        image: rlewan/nginx-static:088822db82ab034a44905030ef7cdfce1cbb68e7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
