---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-static
  namespace: playground
spec:
  template:
    metadata:
      labels:
        app: nginx-static
    spec:
      automountServiceAccountToken: false
      containers:
      - name: nginx-static
        resources:
          requests:
            cpu: 0.5
            memory: "512Mi"
          limits:
            cpu: 1
            memory: "640Mi"
        image: rlewan/nginx-static:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10    # delay after container start and before first liveness probe
          failureThreshold: 10    # times before giving up (before restart pod)
        readinessProbe:
          httpGet:
            path: /
            port: 80
