---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-static-deployment
  namespace: playground
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-static
    spec:
      automountServiceAccountToken: false
      containers:
      - name: nginx-static
        image: rlewan/nginx-static:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10    # delay after container start and before first liveness probe
          failureThreshold: 10    # times before giving up (before restart pod)
        readinessProbe:
          httpGet:
            path: /
            port: 80
